export const WEATHER_CODE = {
  0: { label: "Clear sky", icon: "/images/clear.png" },
  1: { label: "Mainly clear", icon: "/images/clear.png" },
  2: { label: "Partly cloudy", icon: "/images/clouds.png" },
  3: { label: "Overcast", icon: "/images/clouds.png" },
  45: { label: "Fog", icon: "/images/mist.png" },
  48: { label: "Depositing rime fog", icon: "/images/mist.png" },
  51: { label: "Light drizzle", icon: "/images/drizzle.png" },
  53: { label: "Moderate drizzle", icon: "/images/drizzle.png" },
  55: { label: "Dense drizzle", icon: "/images/drizzle.png" },
  56: { label: "Light freezing drizzle", icon: "/images/drizzle.png" },
  57: { label: "Dense freezing drizzle", icon: "/images/drizzle.png" },
  61: { label: "Slight rain", icon: "/images/rain.png" },
  63: { label: "Moderate rain", icon: "/images/rain.png" },
  65: { label: "Heavy rain", icon: "/images/rain.png" },
  66: { label: "Light freezing rain", icon: "/images/rain.png" },
  67: { label: "Heavy freezing rain", icon: "/images/rain.png" },
  71: { label: "Slight snow fall", icon: "/images/snow.png" },
  73: { label: "Moderate snow fall", icon: "/images/snow.png" },
  75: { label: "Heavy snow fall", icon: "/images/snow.png" },
  77: { label: "Snow grains", icon: "/images/snow.png" },
  80: { label: "Slight rain showers", icon: "/images/rain.png" },
  81: { label: "Moderate rain showers", icon: "/images/rain.png" },
  82: { label: "Violent rain showers", icon: "/images/rain.png" },
  85: { label: "Slight snow showers", icon: "/images/snow.png" },
  86: { label: "Heavy snow showers", icon: "/images/snow.png" },
  95: { label: "Thunderstorm", icon: "/images/thunderstorm.png" },
  96: {
    label: "Thunderstorm with slight hail",
    icon: "/images/thunderstorm.png",
  },
  99: {
    label: "Thunderstorm with heavy hail",
    icon: "/images/thunderstorm.png",
  },
};
